### ISSUE TITLE
make dragon block c use traditional hp system instead of it's own

### ISSUE THREAD

**Issue by ominousjrslw** [GTNewHorizons/Hodgepodge#354]
make dragon block c use traditional hp system instead of it's own because when playing with manametalmod it makes impossible to play when you die

**Comment by ominousjrslw** [comment]
and fix already decorating crash with dbc because in even mod that should fix it not fixing it

**Comment by Glease** [comment]
what exactly are you talking about? how does this relate to hodgepodge or GTNH?

**Comment by ominousjrslw** [comment]
don't you fix you any problem not related to gtnh?

**Comment by Glease** [comment]
1. we allow others to contribute code that are completely unrelated to GTNH
2. we sometimes change our code when adding hodgepodge would break an otherwise perfectly fine modpack.

afaik hodgepodge has nothing to do with either of the mod you mentioned, so # 2 is out. you have to find someone (*) interested in your issue to cook up a fix, then we can merge it in hodgepodge.

given the hodgepodge issue tracker isn't a community 1.7.10 wishlist, I'll close the issue now. If a PR doing what you described ever comes up in the future though, it might be merged.

--
*: either outside the gtnh team or inside. as a disclaimer, I'm not interested, since I don't even know what dragon block c is
